name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=M3hul-raj&show_icons=true&theme=tokyonight&custom_title=My%20GitHub%20Stats
          path: profile/stats.svg
          token: ${{ secrets.PAT_1 }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=M3hul-raj&layout=compact&theme=tokyonight&exclude_repo=AQI_ML,DAA_Lab_IMH-10030-22,Probability-and-Statistics-Lab,OPDP_Lab_IMH-10030-22
          path: profile/top-langs.svg
          token: ${{ secrets.PAT_1 }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
